### PR TITLE
Add xz-utils to rootfs

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Just to clarify, you need this in the agent rootfs?

@staticfloat Would it be better to make an YggY-specific rootfs, and then use the sandbox Buildkite plugin to enter that rootfs?

**Comment by vchuravy** [comment]
I think xz is generally useful (like zstd)

**Comment by staticfloat** [comment]
I agree it is generally useful.

**Review by DilumAluthge — APPROVED** [review]

**Comment by giordano** [comment]
In Yggdrasil we [used to have](https://github.com/JuliaPackaging/Yggdrasil/blob/8e7a9c4f1761fcb71c8d2e33688d36ff6fb9f9d2/.ci/azp_agent/install_agents.sh#L21)
```
ssh,curl,libicu63,git,xz-utils,bzip2,unzip,p7zip,zstd,expect,locales,libgomp1
```
In particular we need also bzip2, unzip and p7zip, otherwise uncompressing archives is going to be complicated.

**Comment by vchuravy** [comment]
Can we not replace these with jlls ;)

**Comment by giordano** [comment]
Those needed by tar are tricky (but probably not impossible to deal with, just quite ugly) because tar needs to find everything in PATH. And I don't think we have unzip at all.

**Comment by giordano** [comment]
And unzip is needed right now in https://github.com/JuliaPackaging/Yggdrasil/pull/6079

**Comment by DilumAluthge** [comment]
Let's just make a separate Yggdrasil-specific rootfs image. Then we can add anything we want, without feeling guilty about bloating the base agent image.

I created a PR (https://github.com/JuliaCI/rootfs-images/pull/243), and it includes all the apt packages from https://github.com/JuliaPackaging/Yggdrasil/blob/8e7a9c4f1761fcb71c8d2e33688d36ff6fb9f9d2/.ci/azp_agent/install_agents.sh#L21.

**Comment by DilumAluthge** [comment]
Closing in favor of #243

**Pull request closed without merging**
