### PR TITLE
Update all Linux toolchains

### LINKED ISSUE #178: `armv7l-linux-gnu`: use our own custom `glibc`

### LINKED ISSUE #179: `ppc64le-linux-gnu`: use our own custom `glibc`

### PR DESCRIPTION
**Pull request by staticfloat**
Wahoo!

Fixes #178 
Fixes #179

### CODE REVIEW

**Review by DilumAluthge — CHANGES_REQUESTED** [review]
You also need to uncomment the relevant lines in the workflow file.

**Comment by staticfloat** [comment]
Looks like they're already uncommented to me?

**Comment by DilumAluthge** [comment]
Ah that's right, I forgot that aarch64 was the only arch with that qemu bug.

**Review by DilumAluthge — APPROVED** [review]

**Comment by DilumAluthge** [comment]
armv7 is failing.

**Comment by DilumAluthge** [comment]
Looks like one of the download URLs is incorrect on arm7.

**Comment by DilumAluthge** [comment]
I think the Binutils URL.

**Comment by DilumAluthge** [comment]
Looks like they are still failing.

**Comment by DilumAluthge** [comment]
armv7 is failing, but everything else is passing.

**Comment by DilumAluthge** [comment]
We also shouldn't allow those `curl` commands to exit with zero exit code if the download actually failed.

Can you add `--fail` or `--fail-with-body` to all of those `curl` commands?

**Comment by staticfloat** [comment]
Sure, I'll do that as well, but I think the true problem was a lack of `-e` for `bash`.

**Comment by DilumAluthge** [comment]
We should probably make the `set -eu -o pipefail` addition to all of the scripts that define a `my_chroot` closure.

**Comment by DilumAluthge** [comment]
Alright, looks like `which gcc` is succeeding, but `which g++` is failing.

**Comment by DilumAluthge** [comment]
> We should probably make the `set -eu -o pipefail` addition to all of the scripts that define a `my_chroot` closure.

https://github.com/JuliaCI/rootfs-images/pull/190

**Pull request merged**
