### PR TITLE
Update the version of Git in the `tester_linux` images

### PR DESCRIPTION
**Pull request by DilumAluthge**
This is needed for https://github.com/JuliaLang/Pkg.jl/pull/2946 and https://github.com/JuliaLang/julia/pull/43849.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
From the CI logs:

```
I: Retrieving git 1:2.20.1-2+deb10u3
I: Validating git 1:2.20.1-2+deb10u3
```

So it's still only installing Git version 2.20.1. But we need at least 2.28 for https://github.com/JuliaLang/Pkg.jl/pull/2946 and https://github.com/JuliaLang/julia/pull/43849.

@staticfloat @vchuravy What do you think is the best way for us to install Git 2.28 here?

**Comment by DilumAluthge** [comment]
@staticfloat Should we upgrade our Debian images from Buster to Bullseye? Or would that be an overreaction?

**Comment by staticfloat** [comment]
Yeah, that's an overreaction.  We shouldn't require such a new version of `git` in our tests; I think we need to adjust the `Pkg` commit to be more amenable to older git's.

**Comment by DilumAluthge** [comment]
I'm closing this PR in favor of https://github.com/JuliaLang/Pkg.jl/pull/2949

**Pull request closed without merging**
