### PR TITLE
Re-enable building the `package_linux.aarch64` image

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
For example, `package_linux.armv7l` and `package_linux.powerpc64le` are passing without any problems. And both of those architectures are also using `qemu`.

**Comment by DilumAluthge** [comment]
> I was wondering if maybe https://bugs.launchpad.net/bugs/1928075 is related?

Or maybe https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1924231 instead?

**Comment by DilumAluthge** [comment]
> > I was wondering if maybe https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1928075 is related?
> 
> Or maybe https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1924231 instead?

The stacktrace posted in bug 1924231 looks very similar to the stacktrace we are seeing on this PR.

**Comment by staticfloat** [comment]
Hmmm, I guess you could try [adding backports](https://help.ubuntu.com/community/UbuntuBackports) and trying to install a newer `qemu` in the runner?

**Pull request closed without merging**
