### PR TITLE
Add the `debian_minimal` rootfs image

### PR DESCRIPTION
**Pull request by DilumAluthge**
The `debian_minimal` image contains no packages.

We can use this e.g. for testing in the Sandbox.jl test suite. cc: @staticfloat

### CODE REVIEW

**Comment by staticfloat** [comment]
The sandbox already has this?

**Comment by DilumAluthge** [comment]
> The sandbox already has this?

Yeah, but the Sandbox.jl tests are failing with the current one. I'm wondering if maybe the issue is with the current one (e.g. maybe the apt source list is out of date) so I was thinking of building a new image and trying the tests with that.

**Comment by DilumAluthge** [comment]
@staticfloat Instead of this PR, do you want to just publish a new `debian-minimal` artifact on the Sandbox.jl repo?

**Comment by DilumAluthge** [comment]
I've posted some more info in https://github.com/staticfloat/Sandbox.jl/pull/45

**Pull request merged**
