### PR TITLE
Create a separate rootfs image for Yggdrasil

### PR DESCRIPTION
**Pull request by DilumAluthge**
Closes #242

### CODE REVIEW

**Review by giordano — APPROVED** [review]
It's good for now, I'll look into using JLLs where possible, but at the moment we aren't fully covered yet anyway (e.g. unzip).

**Comment by giordano** [comment]
I'm not sure we really need the extra stuff, it was probably only for running the AZP agents.  What we need on top of the base image are the uncompressing tools.

**Comment by DilumAluthge** [comment]
Yeah, we can remove stuff in future releases if we realize we don't need it. I figured we should first just get a release out, though.

https://github.com/JuliaCI/rootfs-images/releases/tag/v5.52

**Comment by DilumAluthge** [comment]
https://github.com/JuliaCI/rootfs-images/releases/download/v5.52/yggdrasil.x86_64.tar.gz

**Comment by DilumAluthge** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/6102

**Comment by staticfloat** [comment]
> It's good for now, I'll look into using JLLs where possible, but at the moment we aren't fully covered yet anyway (e.g. unzip).

I have @thazhemadam working on a buildkite plugin to allow easy downloading/unpacking of JLLs into a prefix for buildkite plugins: https://github.com/JuliaCI/jack-buildkite-plugin/pull/1/files

**Pull request merged**
